// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://njztfieywurfvghrxvox.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5qenRmaWV5d3VyZnZnaHJ4dm94Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkzMTUzNjIsImV4cCI6MjA1NDg5MTM2Mn0.mdaStCDPTDiAxNNLvOrKtn46MPQ4W6dl_6eslLQYzMk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);